---
- name: Install a specified package on Raspberry Pi
  hosts: raspberrypi
  become: yes
  vars:
    package_name: ""  # Placeholder for the package name

  tasks:
    - name: Install specified package
      ansible.builtin.apt:
        name: "{{ package_name }}"
        state: present

